version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "0.11.8"
    # From https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_SHA256SUMS
    TERRAFORM_SHA256: "84ccfb8e13b5fce63051294f787885b76a1fedef6bdbecf51c5e586c9e20c9b7"

phases:
  install:
    commands:
      - echo "Updating package index" && apt-get update
      - echo "Installing jq" && apt-get install -y jq
      - echo "Installing Terraform ${TERRAFORM_VERSION}" && pushd . && cd /tmp && curl -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && echo "${TERRAFORM_SHA256} terraform.zip" | sha256sum -c --quiet && unzip terraform.zip && mv terraform /usr/bin && popd
  pre_build:
    commands:
      - echo "Nothing to be done in pre_build phase..."
  build:
    commands:
      - pwd
      - ls -lhaR
      - terraform --version
      - terraform init
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'

