version: 0.2

phases:
  install:
    commands:
      - echo "Updating package index" && apt-get update
      - echo "Installing jq" && apt-get install -y jq
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mkdir target
      - touch target/output.txt
      - echo "$(date)" > target/output.txt
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'

